accounts/urls.py
from re import template
from django.urls import path, include

from .views import register

from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('signup/', register, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name="logout"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_complete.html'), name="password_reset_complete"),
]

pages/urls.py
from django.urls import path
from .views import home, about, course_detail, UserInterest, razorpaycheck,success, razorpaycheckmonth

app_name = 'pages'
urlpatterns = [
    path('', home, name='home' ),
    path('about/', about, name='about'),
    path('courses/',course_detail, name='courses' ),
    path('interested/', UserInterest.as_view(), name='join' ),
    path('checkout-onetime/', razorpaycheck, name='checkout'),
    path('checkout-monthly/', razorpaycheckmonth, name='checkout-monthly'),
    path('coding/', UserInterest.as_view(), name='coding'),

 path('checkout-monthly/success/', success, name='checkout-monthly-success'),
    path('checkout-onetime/success/', success, name='checkout-onetime-success'),

]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
] 

accounts/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.urls import reverse
from django.db import models


class UserInfo(models.Model):
    student_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=50)
    mail = models.CharField(max_length=50)
    message = models.TextField(null=True, blank=True)


    def __str__(self):
        return self.student_name

    def get_absolute_url(self):
        return reverse('pages:home')

# class ContactUs(models.Model):
#     email = models.EmailField()

#     def __str__(self):
#         return self.email

#     def get_absolute_url(self):
#         return reverse('pages:home')

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    phone = forms.CharField(max_length=20)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone', 'password1', 'password2']

pages/forms.py
from dataclasses import field
from statistics import mode
from django import forms
from .models import UserInfo


class UserInterestForm(forms.ModelForm):
    # student_name = forms.CharField(max_length=200)
    # mail = forms.EmailField()


    class Meta:
        model = UserInfo
        fields = ['student_name', 'phone', 'mail', 'message']
    
# class ContactMailForm(forms.ModelForm):
    

    # class Meta:
    #     model = ContactUs
    #     fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm


from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from .forms import UserRegisterForm

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


def register(request):

    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'account/signup.html', {'form': form})

pages/views.py
from django.views.generic.edit import CreateView
from django.shortcuts import render

from django.contrib.auth.decorators import login_required




import razorpay
from .models import UserInfo

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')


def course_detail(request):
    return render(request, 'courses.html')

@login_required
def razorpaycheck(request):
    if request.method == "POST":
        order_amount = 699
        order_currency = "INR"
        client = razorpay.Client(auth=('rzp_live_Wk8Xsfot2Nw2zA', 'LmyqZxDxN92tWDKlzWqsx306'))
        payment = client.order.create({'amount': order_amount, 'currency': order_currency, 'payment_capture': "1"})
    return render(request, 'checkout.html')

@login_required
def razorpaycheckmonth(request):
    if request.method == "POST":
        order_amount = 299
        order_currency = "INR"
        client = razorpay.Client(auth=('rzp_live_Wk8Xsfot2Nw2zA', 'LmyqZxDxN92tWDKlzWqsx306'))
        payment = client.order.create({'amount': order_amount, 'currency': order_currency, 'payment_capture': "1"})
    return render(request, 'checkoutmonth.html')


class UserInterest(CreateView):
    template_name = 'join.html'
    model = UserInfo
    fields = ['student_name', 'phone', 'mail',]

def success(request):
    return render(request, 'success.html')

templates/about.html
{% extends "base.html" %}


{% block content %}
<div class="container-fluid about bg-dark text-light">
    <div class="row text-center  ">
        <h1>About Me</h1>
        <div class="col-md-5 col-xs-12">
            <img class="img-col"
                src="https://img.freepik.com/free-vector/hacker-operating-laptop-cartoon-icon-illustration-technology-icon-concept-isolated-flat-cartoon-style_138676-2387.jpg?size=338&ext=jpg"
                style="width: 300px; height: 300px; border-radius:50%" alt="">
        </div>
        <div class="col-md-6 col-xs-12 p-3">
            <h1>Karan Patil</h1>
            <h3 class="fst-italic text-muted">Programmer, IIT Madras Student</h3>
            <p>A self taught Programmer currently pursuing B.S Degree in Data Science from IIT Madras. Passionate about
                learning new skills.Fond of Computer Science and Technology. Teaching maths for past 2 years.</p>
        </div>
    </div>
    <div class="row text-center bg-light text-dark mt-4 pt-5">
        <h1>About Codepat</h1>
        <div class="col-md-6 col-xs-12 p-3">
            <h1>CodePat</h1>
            <h3 class="fst-italic text-muted">A platform to learn coding.</h3>
            <p>Built with the knowlegde I gained over the years of learning how to code this platform is my contribution
                to teach others how to make awesome products for yourself and for the society.</p>
        </div>
        <div class="col-md-5 col-xs-12">
            <img class="img-col"
                src="https://images.pexels.com/photos/340152/pexels-photo-340152.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                style="width: 300px; height: 300px; border-radius:50%" alt="">
        </div>


    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}


<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Karan Patil</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Acme&family=Lobster&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,700;0,800;0,900;1,100;1,200;1,700&family=Patua+One&family=Rubik&family=Sniglet&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
    {% block style %}

    {% endblock style %}
    <link rel="stylesheet" href="/home/veah6juaasmp/thecodepat/staticfiles/css/main.css">
    <link rel="stylesheet" href="/home/veah6juaasmp/thecodepat/staticfiles/css/style.css">
    <link rel="stylesheet" href="/home/veah6juaasmp/thecodepat/staticfiles/css/mobile-style.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %} ">
    <link rel="stylesheet" href="{% static 'css/mobile-style.css' %} ">
</head>



<body>
    <nav class="navbar navbar-expand-lg fixed-top nav-bg">
        <div class="container-fluid">
            <div class="mr-4">
                <a class="logo" href="{% url 'pages:home' %}"><i class="fa-solid fa-code"></i> CodePat</a>

            </div>
            {% if user.is_authenticated %}
            <p class="d-inline d-md-none text-light nav-link navli pt-2">Hi {{ user.username }}!</p>
            {% endif %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav ms-auto me-3 mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link  navli" aria-current="page" href="{% url 'pages:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link navli" aria-current="page" href="{% url 'pages:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link navli" aria-current="page" href="{% url 'pages:courses' %}">Courses</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span><a class="nav-link navli" href="{% url 'accounts:logout' %}">Logout</a></span>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link navli" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link navli" aria-current="page" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>

                    {% endif %}
                </ul>
            </div>
        </div>

    </nav>
    {% if messages %}
    {% for message in messages %}



    <div class="alert alert-{{ message.tags }} courses" style=" z-index: 5;">
        {{message}}
    </div>
    {% endfor %}

    {% endif %}
    {% block content %}

    {% endblock content %}


    <footer>
        <div class="container-fluid">
            <div class="row text-left">
                <div class="col-md-5">
                    <h1 class="text-light">About</h1>
                    <p class="text-muted">A self taught Programmer currently pursuing B.S Degree in Data Science from
                        IIT Madras. <a href="{% url 'pages:about' %}">Know more.</a></p>
                    <p class="pt-4 text-muted">
                        Copyright &copy;2022 All rights reserved | <span>Karan Patil.</span>
                    </p>
                </div>
                <div class="col-md-5">
                    <h4 class="text-light">Send Me</h4>
                    <p class="text-muted">Contact us so we can reach you.</p>
                    <div class="row p-3">
                        <div class="col-md-5 text-light fw-bold">+91 8329739071</div>
                        <div class="col-md-5 text-light fst-italic">karanpatil1604@gmail.com</div>
                    </div>

                </div>
                <div class="col-md-2 col-sm-12">
                    <h4 class="text-light">Follow Us</h4>
                    <p class="text-muted">Let us be social</p>
                    <div class=" column text-right">
                        <a href="https://www.facebook.com/profile.php?id=100036282139209" target="_blank"
                            class="px-2"><i class="fab fa-facebook-f"></i></a>
                        <a href="https://www.instagram.com/karan.patil11/" target="_blank" class="px-2"><i
                                class="fab fa-instagram"></i></a>
                        <a href="https://twitter.com/KaranPa10882433" target="_blank" class="px-2"><i
                                class="fab fa-twitter"></i></a>

                    </div>
                    <div class="pt-2 mt-2">
                         <a href="https://merchant.razorpay.com/policy/KbIDD2pQbm2aBe/privacy">Privacy</a>
    <a href="https://merchant.razorpay.com/policy/KbIDD2pQbm2aBe/terms">terms</a>
    <a href="https://merchant.razorpay.com/policy/KbIDD2pQbm2aBe/refund">refund</a>
    <a href="https://merchant.razorpay.com/policy/KbIDD2pQbm2aBe/shipping">shipping</a>
    <a href="https://merchant.razorpay.com/policy/KbIDD2pQbm2aBe/contact_us">contact_us</a>

                    </div>
                </div>
            </div>
    </footer>



    <!-- scripts -->
    <script src="https://kit.fontawesome.com/c68135ad63.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"
        integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
        integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
        crossorigin="anonymous"></script>
    <!-- scripts end -->



</body>

</html>

templates/courses.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/style.css' %} ">
<link rel="stylesheet" href="{% static 'css/mobile-style.css' %} ">
{% endblock style %}

{% block content %}

<header>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <h6>TUTOR: KARAN PATIL</h6>
                <h1>CODEPAT LEARNING:Maths for Class 12</h1>
                <p>Learn mathematics from a completely different perspective. You will fall in love with the beauty of
                    maths. Learn with the help of new gen technology and eternal curiosity. Online Maths classes for
                    12th State Board Exam. See below for more features.</p>
                <button class="btn btn-light px-5 py-2"> <a class="text-dark text-decoration-none"
                        href="{% url 'pages:checkout' %}"> Join Now ₹699
                        for full course</a></button>
            </div>

        </div>
    </div>
</header>




<main>


    <!-- section2 -->
    <section class="section-2 container-fluid p-0">
        <div class="cover">
            <div class="container text-center">
                <h1>Some Features That make us Unique</h1>
               <p>We believe in delivering excellence. </p>
            </div>
        </div>
        <div class="container-fluid text-center">
            <div class="numbers d-flex flex-md-row flex-wrap justify-content-center">
                <div class="rect">
                    <h1>Online</h1>
                    <p>Learn at your Place. LIVE on Gmeet!</p>
                </div>
                <div class="rect">
                    <h1>100%</h1>
                    <p>Refund:If scores don't improve.</p>
                </div>
                <div class="rect">
                    <h1>Class 12</h1>
                    <p>Improve your score by 15% to 25%</p>
                </div>
                <div class="rect">
                    <h1>3 Days Trial</h1>
                    <p>Cancel if you don't get value.</p>
                </div>
            </div>
        </div>
        <div class="purchase text-center p-2">
            <h1>purchase however you want</h1>
            <p>You can choose to pay monthly or one time payment for the complete course. Offer is only valid for the
                one time payment option.</p>
            <div class="cards">
                <div class="d-flex flex-row justify-content-center flex-wrap">

                    <!-- first card -->
                    <div class="card" style="width: 28rem;">
                        <div class="card-body">
                            <div class="title">
                                <h5 class="card-title">Monthly</h5>
                            </div>
                            <p class="card-text">Pay for each month as you go. Recurring payment option gives you more
                                flexibility.</p>
                            <div class="pricing">
                                <h2 class="text-decoration-line-through">₹399</h2>
                                <h1>₹299 <small class="text-muted fs-5">/month</small> </h1>
                                <a class="btn btn-dark px-5 py-2 mb-5" href="{% url 'pages:checkout-monthly'%}">Enroll
                                    Now</a>
                            </div>

                        </div>
                    </div>
                    <!-- second card -->
                    <div class="card" style="width: 28rem;">
                        <h3><span class="badge text-bg-danger mt-3">Recommended</span></h3>
                        <div class="card-body">
                            <div class="title">
                                <h5 class="card-title">Complete Course</h5>
                            </div>
                            <p class="card-text">A great opportunity for you to take a high-worth course at this
                                affordable fees. Grab your chance now!</p>
                            <div class="pricing">
                                <h2 class="text-decoration-line-through">₹999</h2>
                                <h1>₹699 <small class="text-muted fs-5">One Time Purchase</small> </h1>
                                <a class="btn btn-dark px-5 py-2 mb-5" href="{% url 'pages:checkout'%}">Enroll
                                    Now</a>
                            </div>

                        </div>
                    </div>
                    <!-- pricing cards end -->

                </div>
            </div>
        </div>
    </section>
    <!-- 
    <section class="section-1">
        <div class="container text-ceter">
            <div class="row">
                <div class="col-md-6 not-mobile">
                    <div class="pray">
                        <img src="https://images.pexels.com/photos/5412361/pexels-photo-5412361.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                            alt="">
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="panel text-left">
                        <h1>Mr. KARAN PATIL</h1>
                        <p class="pt4">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo, nihil
                            doloribus quia, voluptas, amet tenetur tempore suscipit esse adipisci hic eos temporibus
                            optio aspernatur velit. Inventore cumque sed ullam atque.</p>
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Saepe, vel illum exercitationem
                            cupiditate, laudantium soluta at consequatur pariatur illo molestias ea debitis,
                            accusantium deserunt eaque rem temporibus. Id, fugiat voluptatem quibusdam tenetur
                            excepturi culpa quisquam quasi nam adipisci odit voluptate. Aspernatur laudantium ullam
                            mollitia odit sunt amet, aut nesciunt explicabo totam vitae ipsum, temporibus saepe?
                            Provident eligendi excepturi ut recusandae.</p>
                    </div>
                </div>
            </div>
        </div>
    </section> -->

    <section class="section-3 container-fluid p-0">
        <div class="container text-center pt-4">
            <h1 class="text-dark">Quotes</h1>
            <p class="text-secondary">Some things are said for the sake of history.
            </p>
        </div>
        <div class="team row">
            <div class="col-md-4 col-12 text-center">

                <!-- Quote cards -->
                <div class="card">

                    <div class="card-body">
                        <h3 class="card-title">Edsger W. Dijkstra</h3>
                        <p class="text-black-50">Dutch systems scientist</p>
                        <p class="card-text">There should be no such thing as boring mathematics.</p>

                    </div>
                </div>

            </div>
            <div class="col-md-4">
                <!-- Carousel Start -->
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active text-center">
                            <!-- Card 2 carousel 1 -->
                            <div class="card  shadow-lg">
                                <div class="card-body">
                                    <h3 class="card-title">Albert Einstein</h3>
                                    <p class="text-black-50">German Physicist</p>
                                    <p class="card-text">As far as the laws of mathematics refer to reality, they are
                                        not certain, and as far as they are certain, they do not refer to reality.</p>

                                </div>
                            </div>
                        </div>
                        <!-- card 3 carousel 2 -->
                        <div class="carousel-item text-center">
                            <div class="card  shadow-lg">
                                <div class="card-body">
                                    <h3 class="card-title">Shakuntala Devi</h3>
                                    <p class="text-black-50">Indian writer and mental calculator</p>
                                    <p class="card-text">Without mathematics, there’s nothing you can do. Everything
                                        around you is mathematics. Everything around you is numbers.</p>

                                </div>
                            </div>


                        </div>

                    </div>
                </div>
                <!-- Carousel End -->
            </div>

            <div class="col-md-4 col-12">
                <!-- Card 4 -->
                <div class="card text-center">

                    <div class="card-body">
                        <h3 class="card-title">John von Neumann</h3>
                        <p class="text-black-50">Hungarian-American mathematician</p>
                        <p class="card-text">If people do not believe that mathematics is simple, it is only because
                            they do not realize how complicated life is.</p>

                    </div>
                </div>
            </div>
        </div>
    </section>
</main>




{% endblock content %}

templates/home.html
{% extends "base.html" %}


{% block content %}

<div class="container-fluid p-0 cleared">
    <!-- Carousel start  -->
    <div id="carouselExampleCaptions" class="carousel slide" style="height: 70vh;" data-bs-ride="false">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://images.pexels.com/photos/4974912/pexels-photo-4974912.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                    class="d-block w-100 img-fluid image" style="height: 70vh;" alt="...">
                <div class="carousel-caption d-md-block caption1">
                    <h3>Computer Programming</h3>
                    <h5>The best way to talk to dumb computers and make them smart.</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img src="https://img.freepik.com/free-vector/math-science-concept-with-school-lesson-items-retro-cartoon-style_1284-8084.jpg?size=338&ext=jpg"
                    class="d-block w-100 img-fluid image" style="height: 70vh;" alt="...">
                <div class="carousel-caption d-md-block caption2">
                    <h3>Mathematics</h3>
                    <h5>Build your fundamentals strong.</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img src="https://images.unsplash.com/photo-1633356122544-f134324a6cee?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
                    class="d-block w-100 image" style="height: 70vh;" alt="...">
                <div class="carousel-caption d-md-block caption3">
                    <h3>Build Web-apps</h3>
                    <h5>Let's create some awesome products out of our knowledge.</h5>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <!-- Carousel End -->





    <!-- Card Items start -->
    <div class="container-fluid p-4 mt-3">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card shadow">
                    <img src="https://img.freepik.com/free-vector/maths-chalkboard_23-2148178219.jpg?size=626&ext=jpg"
                        class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Learn Mathematics</h5>
                        <p class="card-text">Ace in mathematics with this course. Designed specially for state board
                            exams of 10+2 levels. Guaranteed score improvement.</p>
                        <a href="{% url 'pages:courses' %}" class="btn btn-primary">Know more</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow">
                    <img src="https://img.freepik.com/free-vector/web-development-programmer-engineering-coding-website-augmented-reality-interface-screens-developer-project-engineer-programming-software-application-design-cartoon-illustration_107791-3863.jpg?size=626&ext=jpg"
                        class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Learn Web Development</h5>
                        <p class="card-text">Build real life projects using <strong>Django</strong>. Learn Frontend
                            framework such as <strong>Bootstrap</strong> and <strong>reactjs</strong>.</p>
                        <a href="{% url 'pages:coding' %}" class="btn btn-primary">Know More</a>
                    </div>
                </div>
            </div>


        </div>
    </div>

</div>
<!-- Card Items end -->
{% endblock content %}

templates/join.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section courses mb-4">
    <div class="row text-center">
        <h1>We are starting soon. Contact us for more!</h1>
    </div>
    <div class="row p-4 m-4">
        <div class="col ">
            <h1 class="text-center">Contact form</h1>
            <div class="form-group">
                <p class="lead">Fill out this form and we will get back to you.</p>
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div class="form-group">
                        <button type="submit" value="save" class="btn btn-outline-info">Join Now</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% load account %}
{% load i18n %}
{% load account socialaccount %}
{% user_display user %}

{% block content %}
<div class="container-fluid courses">

    <div class="card shadow mt-3">
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">
                        <h3>Sign Up Now</h3>
                    </legend>
                    {{ form| crispy}}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-info">Sign Up</button>
                </div>
            </form>
            <div class="container">
                <small class="text-muted">Already Have an account?</small>
                <a class="btn btn-outline-success" href="{% url 'accounts:login' %}">Login</a>
            </div>
        </div>

    </div>
    <div class="container">
        {% comment %} Or sign up using google using google <a href="{% url 'account_login' %}"></a> {% endcomment %}
    </div>

</div>
{% endblock content %}

templates/success.html
{% extends "base.html" %}


{% block content %}
<div class="container-fluid courses">
    <div class="card shadow mt-3">
        <div class="card-body">

            <h1>Thank You!</h1>
<p>Your payment recieved successfully you can go to home page now or close this page.
<a href=
"{% url 'pages:home' %}">Go to homepage</a>.</p>
        </div>

    </div>

{% endblock content %}